version: "3.5"

volumes:
  app-deps:
  app-build:

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  app:
    tty: true
    build:
      context: .
    command: sh -c 'while true; do sleep 60; done'
    environment:
      DATABASE_HOSTNAME: postgres
    working_dir: /app
    ports:
      - 4000:4000
    volumes:
      - .:/app:cached
      - app-deps:/app/deps
      - app-build:/app/_build
    depends_on:
      - postgres
