name: Bank CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: "23.x"
          elixir-version: "1.11"

      - name: Get deps cache
        uses: actions/cache@v1
        with:
          path: deps/
          key: ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-deps-

      - name: Get build cache
        uses: actions/cache@v1
        with:
          path: _build/test/
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Install dependencies
        run: mix deps.get

      - name: Run Formatter
        run: mix format --check-formatted

      - name: Run Linter
        run: mix credo --strict

  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: "22.2"
          elixir-version: "1.11"

      - name: Get deps cache
        uses: actions/cache@v1
        with:
          path: deps/
          key: ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-deps-

      - name: Get build cache
        uses: actions/cache@v1
        with:
          path: _build/test/
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Configures application
        run: mix setup

      - name: Run Tests
        run: mix coveralls.github

  deploy:
    needs: [lint, test]
    if: github.ref == 'refs/heads/master'

    env:
      MIX_ENV: prod
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - uses: mhanberg/gigalixir-action@<current release>
        with:
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          GIGALIXIR_APP: stone-bank
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
